# Site settings
# in the templates available like {{ site.myvariable }}.
title: Site Under Construction
email: your-email@domain.com
brand: Papel Y Diseno
headline: Inventor, Engineer and Futurist
description: > # this means to ignore newlines until "baseurl:"
  Papel Y Diseno
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://papelydiseno.com" # the base hostname & protocol for your site
copyright: 2019 Papel Y Diseno. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 680475

# Contacts
email: p a p e l y d i s e n o @ g m a i l . c o m
phone: +1-800-555-2016

# Tracking
googleAnalitycsID: 

